on:
  push:
    branches:
      - 'main'
  pull_request:
    types:
    - opened
    - reopened
    - synchronize
    - ready_for_review

name: Verify

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
	if: github.event.pull_request.draft == false
    steps:
      - name: install elan
        run: |
          set -o pipefail
          curl -sSfL https://github.com/leanprover/elan/releases/download/v1.4.2/elan-x86_64-unknown-linux-gnu.tar.gz | tar xz
          ./elan-init -y --default-toolchain none
          echo "$HOME/.elan/bin" >> $GITHUB_PATH

      - uses: actions/checkout@v4

      - name: build std
        id: build
        run: lake build -Kwerror
