on:
  push:
    branches:
      - 'main'
  pull_request:
    types:
    - opened
    - reopened
    - synchronize
    - ready_for_review

name: Extract, build, run

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
	if: ${{ github.event_name == 'push' || !github.event.pull_request.draft }}
    steps:
      - name: install elan
        run: |
          set -o pipefail
          curl -sSfL https://github.com/leanprover/elan/releases/download/v1.4.2/elan-x86_64-unknown-linux-gnu.tar.gz | tar xz
          ./elan-init -y --default-toolchain none
          echo "$HOME/.elan/bin" >> $GITHUB_PATH

      - uses: actions/checkout@v4

      - name: install Dafny
        run: wget https://github.com/dafny-lang/dafny/releases/download/v4.4.0/dafny-4.4.0-x64-ubuntu-20.04.zip ; unzip dafny-4.4.0-x64-ubuntu-20.04.zip

      - name: install Python dependences
        run: pip install matplotlib numpy scipy

      - name: build std
        id: build
        run: lake build -Kwerror FastExtract

      - name: build Python version of SampCert
        run: dafny/dafny build --target:py Tests/SampCert.dfy Tests/Random.py Tests/testing-kolmogorov-discretegaussian.py -o Tests/SampCert.dfy

      - name: run Test
        run: python3 Tests/SampCert-py/testing-kolmogorov-discretegaussian.py
